import './sass/main.scss';
import './scripts/api-service';
import './scripts/fetch';
import './scripts/gallery';
import './scripts/components/backToTop';
import './scripts/searchbox';
import './scripts/components/darkTheme';
import './scripts/team';
import './scripts/team-modal';
